### ISSUE TITLE
php MVC framework not working in path

### ISSUE THREAD

**Issue by rezaakbari23** [vafakaramzadegan/scriptshot.ir#1]
Hi

I downloaded PHP framework code and configured database username & pass.
but does not work.

for example:
I use xampp and put the source code in htdoct/framework

not in my browser i go to localhost/framework/[CONTROLLER]/[VIEW]

but the framework does not work. i think that there is a problem with router.

thank you for your help. good luck

**Comment by vafakaramzadegan** [comment]
Hi Reza,

Thanks for watching tutorials and using the code.

I'm not sure exactly what you're up to. but tweaking the `Router` class may fix the issue in this particular case:

```php
class Router{
    ...
    public function __construct(){
        $request_uri = $this->parse($_SERVER['REQUEST_URI']);
        $path_mask = $this->parse('/framework');

        $this->requestURI = array_diff_assoc($request_uri, $path_mask);
    }
    ...
}
```

Explanation:
Assuming that the code is placed somewhere like `htdocs\api`, the Router class should be able to ignore `\api` and then look for `controller` and `action` parameters.
so, using `array_diff_assoc` function, we can easily remove predefined URL prefixes.
additionally, you can define URL prefix as a constant in your `config.php` file or try to find a more dynamic way to get around the issue.

**Comment by rezaakbari23** [comment]
Thank you. it works now!!!
